name: PuddingAPI
version: ${project.version}
main: me.fridtjof.puddingapi.bukkit.PuddingAPI
api-version: 1.19
authors: [Fridtjof_DE]
description: Fridtjof_DE's Java API
website: https://www.fridtjof.me/

commands:
  puddingapi:
    description: PuddingAPI...

permissions:
  puddingapi.update:
    description: Grants permission to get the update message.